//! Scientific acceptance tests use analytic signals and independent expected
//! fractions/variance, not outputs generated by the quality implementation.
mod support;
use domain::{Channel, ChannelKind, UnitInterval};
use eeg_quality::{QualityAnalyzer, QualityConfig};
use support::*;

#[test]
fn clean_sine_has_correct_variance_and_high_quality() {
    let input = recording(256.0, vec![sine(256.0, 10.0, 20.0, 1024)]);
    let before = input.clone();
    let result = analyzer().assess_detailed(&input, &context()).unwrap();
    let m = &result.measurements["Ch0"];
    close(m.variance_uv2.unwrap(), 20.0_f64.powi(2) / 2.0, 1e-5);
    assert_eq!(m.noisy_fraction, UnitInterval::ZERO);
    assert_eq!(m.missing_fraction, UnitInterval::ZERO);
    assert_eq!(m.spectral_windows, 2);
    assert_eq!(m.spectral_coverage, UnitInterval::ONE);
    assert!(result.signal_quality.overall_score.get() > 0.999999);
    assert!(result.signal_quality.bad_channels.is_empty());
    assert!(
        result.signal_quality.channel_quality["Ch0"]
            .warnings
            .is_empty()
    );
    assert_eq!(input, before);
}

#[test]
fn flatline_low_variance_and_overlapping_artifacts_are_not_double_counted() {
    let input = recording(256.0, vec![vec![300.0; 1024]]);
    let result = analyzer().assess_detailed(&input, &context()).unwrap();
    let m = &result.measurements["Ch0"];
    assert_eq!(m.variance_uv2, Some(0.0));
    assert_eq!(m.flatline_fraction, UnitInterval::ONE);
    assert_eq!(m.extreme_amplitude_fraction, UnitInterval::ONE);
    assert_eq!(m.variance_anomaly_fraction, UnitInterval::ONE);
    assert_eq!(m.noisy_fraction, UnitInterval::ONE);
    assert_eq!(m.line_power_fraction, Some(UnitInterval::ZERO));
    let q = &result.signal_quality.channel_quality["Ch0"];
    assert_eq!(q.score, UnitInterval::ZERO);
    for code in [
        "FLATLINE",
        "EXTREME_AMPLITUDE",
        "VARIANCE_ANOMALY",
        "BAD_CHANNEL",
    ] {
        assert!(has_warning(q, code));
    }
}

#[test]
fn plateau_detection_crosses_epoch_boundaries_and_honors_minimum_duration() {
    let mut row = sine(256.0, 10.0, 20.0, 1024);
    row[400..700].fill(123.0);
    row[800..810].fill(123.0); // Too short for the flatline rule.
    let result = analyzer()
        .assess_detailed(&recording(256.0, vec![row]), &context())
        .unwrap();
    close(
        result.measurements["Ch0"].flatline_fraction.get(),
        300.0 / 1024.0,
        1e-12,
    );
    close(
        result.measurements["Ch0"].noisy_fraction.get(),
        300.0 / 1024.0,
        1e-12,
    );
    assert_eq!(result.signal_quality.bad_channels, ["Ch0"]);
}

#[test]
fn extreme_amplitude_counts_boundary_samples_and_both_polarities() {
    let mut row = sine(256.0, 10.0, 20.0, 1024);
    row[13] = 200.0;
    row[14] = -201.0;
    let result = analyzer()
        .assess_detailed(&recording(256.0, vec![row]), &context())
        .unwrap();
    close(
        result.measurements["Ch0"].extreme_amplitude_fraction.get(),
        2.0 / 1024.0,
        1e-12,
    );
    close(
        result.measurements["Ch0"].noisy_fraction.get(),
        2.0 / 1024.0,
        1e-12,
    );
}

#[test]
fn high_and_low_epoch_variance_are_detected_independently_of_amplitude() {
    let mut config = time_only();
    config.extreme_amplitude_uv = 1000.0;
    let input = recording(
        256.0,
        vec![sine(256.0, 10.0, 180.0, 512), sine(256.0, 10.0, 0.05, 512)],
    );
    let result = QualityAnalyzer::new(config)
        .unwrap()
        .assess_detailed(&input, &context())
        .unwrap();
    for label in ["Ch0", "Ch1"] {
        assert_eq!(
            result.measurements[label].variance_anomaly_fraction,
            UnitInterval::ONE
        );
        assert_eq!(
            result.measurements[label].extreme_amplitude_fraction,
            UnitInterval::ZERO
        );
        assert!(has_warning(
            &result.signal_quality.channel_quality[label],
            "VARIANCE_ANOMALY"
        ));
    }
}

#[test]
fn nan_and_infinity_are_measured_not_imputed_or_passed_into_fft() {
    let mut input = recording(256.0, vec![sine(256.0, 10.0, 20.0, 1024)]);
    input.samples[0][0] = f32::NAN;
    input.samples[0][1] = f32::INFINITY;
    input.samples[0][2] = f32::NEG_INFINITY;
    let result = analyzer().assess_detailed(&input, &context()).unwrap();
    let m = &result.measurements["Ch0"];
    close(m.missing_fraction.get(), 3.0 / 1024.0, 1e-12);
    assert_eq!(m.finite_sample_count, 1021);
    assert_eq!(m.noisy_fraction, UnitInterval::ZERO);
    assert_eq!(m.spectral_windows, 1);
    assert_eq!(m.spectral_coverage.get(), 0.5);
    assert!(has_warning(
        &result.signal_quality.channel_quality["Ch0"],
        "MISSING_SAMPLES"
    ));
    assert!(!has_warning(
        &result.signal_quality.channel_quality["Ch0"],
        "INSUFFICIENT_SPECTRAL_COVERAGE"
    ));
    assert!(input.samples[0][0].is_nan());
    assert_eq!(input.samples[0][1], f32::INFINITY);
    serde_json::to_string(&result).unwrap();
}

#[test]
fn all_missing_channel_scores_zero_with_unavailable_spectral_evidence() {
    let mut input = recording(256.0, vec![vec![0.0; 1024]]);
    input.samples[0].fill(f32::NAN);
    let result = analyzer().assess_detailed(&input, &context()).unwrap();
    let m = &result.measurements["Ch0"];
    assert_eq!(m.missing_fraction, UnitInterval::ONE);
    assert_eq!(m.noisy_fraction, UnitInterval::ZERO);
    assert_eq!(m.variance_uv2, None);
    assert_eq!(m.line_power_fraction, None);
    assert_eq!(result.signal_quality.overall_score, UnitInterval::ZERO);
    assert!(has_warning(
        &result.signal_quality.channel_quality["Ch0"],
        "NO_VALID_SPECTRAL_WINDOWS"
    ));
}

#[test]
fn missing_sample_breaks_flatline_run() {
    let mut input = recording(256.0, vec![vec![123.0; 256]]);
    input.samples[0][127] = f32::NAN;
    let mut config = time_only();
    config.variance.minimum_uv2 = 0.0;
    config.flatline.minimum_duration_seconds = 0.75;
    let result = QualityAnalyzer::new(config)
        .unwrap()
        .assess_detailed(&input, &context())
        .unwrap();
    assert_eq!(
        result.measurements["Ch0"].flatline_fraction,
        UnitInterval::ZERO
    );
}

#[test]
fn explicit_50_and_60_hz_mains_frequency_is_detected() {
    for frequency in [50.0, 60.0] {
        let mut config = QualityConfig::default();
        config.spectral.line_frequency_hz = Some(frequency);
        let input = recording(256.0, vec![sine(256.0, frequency, 20.0, 1024)]);
        let result = QualityAnalyzer::new(config)
            .unwrap()
            .assess_detailed(&input, &context())
            .unwrap();
        close(
            result.measurements["Ch0"]
                .line_power_fraction
                .unwrap()
                .get(),
            1.0,
            1e-10,
        );
        assert!(has_warning(
            &result.signal_quality.channel_quality["Ch0"],
            "POWER_LINE_INTERFERENCE"
        ));
        assert_eq!(result.signal_quality.bad_channels, ["Ch0"]);
    }
}

#[test]
fn wrong_mains_frequency_does_not_claim_line_interference() {
    let input = recording(256.0, vec![sine(256.0, 60.0, 20.0, 1024)]);
    let result = analyzer().assess_detailed(&input, &context()).unwrap();
    assert!(
        result.measurements["Ch0"]
            .line_power_fraction
            .unwrap()
            .get()
            < 1e-10
    );
    assert!(!has_warning(
        &result.signal_quality.channel_quality["Ch0"],
        "POWER_LINE_INTERFERENCE"
    ));
    assert!(has_warning(
        &result.signal_quality.channel_quality["Ch0"],
        "HIGH_FREQUENCY_NOISE"
    ));
}

#[test]
fn high_frequency_and_nyquist_bins_use_correct_one_sided_weights() {
    // 80 Hz sine has variance A²/2; Nyquist cosine alternates ±A and has
    // variance A². Both should have all power above the 30 Hz boundary.
    let input = recording(
        256.0,
        vec![
            sine(256.0, 80.0, 20.0, 1024),
            (0..1024)
                .map(|n| if n % 2 == 0 { 20.0 } else { -20.0 })
                .collect(),
        ],
    );
    let result = analyzer().assess_detailed(&input, &context()).unwrap();
    for label in ["Ch0", "Ch1"] {
        close(
            result.measurements[label]
                .high_frequency_power_fraction
                .unwrap()
                .get(),
            1.0,
            1e-10,
        );
        assert!(has_warning(
            &result.signal_quality.channel_quality[label],
            "HIGH_FREQUENCY_NOISE"
        ));
    }
    close(
        result.measurements["Ch1"].variance_uv2.unwrap(),
        400.0,
        1e-10,
    );
}

#[test]
fn units_are_converted_for_measurement_without_changing_input() {
    let base = sine(256.0, 10.0, 20.0, 1024);
    for (unit, divisor) in [
        ("uV", 1.0),
        ("µV", 1.0),
        ("μV", 1.0),
        ("mV", 1e3),
        ("V", 1e6),
    ] {
        let mut input = recording(
            256.0,
            vec![
                base.iter()
                    .map(|value| (f64::from(*value) / divisor) as f32)
                    .collect(),
            ],
        );
        input.channels[0].unit = unit.into();
        let before = input.clone();
        let result = analyzer().assess_detailed(&input, &context()).unwrap();
        close(
            result.measurements["Ch0"].variance_uv2.unwrap(),
            200.0,
            2e-5,
        );
        assert!(result.signal_quality.overall_score.get() > 0.999999);
        assert_eq!(input, before);
    }
}

#[test]
fn auxiliary_channels_are_excluded_and_bad_eeg_remains_in_overall_score() {
    let mut input = recording(
        256.0,
        vec![
            sine(256.0, 10.0, 20.0, 1024),
            vec![0.0; 1024],
            vec![0.0; 1024],
        ],
    );
    input.channels[2] = Channel::new("Trigger", ChannelKind::Trigger, "code").unwrap();
    input.samples[2].fill(f32::NAN); // Outside EEG scope, not a quality penalty.
    let result = analyzer().assess_detailed(&input, &context()).unwrap();
    assert_eq!(result.excluded_channels, ["Trigger"]);
    assert_eq!(result.signal_quality.channel_quality.len(), 2);
    assert_eq!(result.signal_quality.bad_channels, ["Ch1"]);
    close(result.signal_quality.overall_score.get(), 0.5, 1e-10);
}

#[test]
fn short_low_rate_and_sparse_valid_data_cannot_silently_score_as_clean() {
    for (rate, count, expected_code) in [
        (256.0, 100, "NO_VALID_SPECTRAL_WINDOWS"),
        (80.0, 320, "LINE_BAND_UNAVAILABLE"),
        (50.0, 200, "HIGH_FREQUENCY_BAND_UNAVAILABLE"),
    ] {
        let result = analyzer()
            .assess_detailed(
                &recording(rate, vec![sine(rate, 10.0, 20.0, count)]),
                &context(),
            )
            .unwrap();
        assert!(has_warning(
            &result.signal_quality.channel_quality["Ch0"],
            expected_code
        ));
        assert!(result.signal_quality.overall_score.get() <= 0.5);
        assert_eq!(result.signal_quality.bad_channels, ["Ch0"]);
    }
    let mut input = recording(256.0, vec![sine(256.0, 10.0, 20.0, 2048)]);
    for index in [0, 512, 1024] {
        input.samples[0][index] = f32::NAN;
    }
    let result = analyzer().assess_detailed(&input, &context()).unwrap();
    assert_eq!(result.measurements["Ch0"].spectral_coverage.get(), 0.25);
    assert!(has_warning(
        &result.signal_quality.channel_quality["Ch0"],
        "INSUFFICIENT_SPECTRAL_COVERAGE"
    ));
    assert!(result.signal_quality.overall_score.get() <= 0.5);
}

#[test]
fn tail_is_checked_for_artifacts_but_not_padded_into_spectral_evidence() {
    let mut row = sine(256.0, 10.0, 20.0, 512);
    row.extend(vec![300.0; 128]);
    let result = analyzer()
        .assess_detailed(&recording(256.0, vec![row]), &context())
        .unwrap();
    let m = &result.measurements["Ch0"];
    assert_eq!(m.spectral_windows, 1);
    assert_eq!(m.spectral_coverage.get(), 0.8);
    assert_eq!(m.noisy_fraction.get(), 0.2);
    assert_eq!(result.signal_quality.bad_channels, ["Ch0"]);
}

#[test]
fn finite_f32_extremes_produce_finite_quality_and_variance() {
    let mut input = recording(
        256.0,
        vec![
            (0..512)
                .map(|n| if n % 2 == 0 { f32::MAX } else { -f32::MAX })
                .collect(),
        ],
    );
    input.channels[0].unit = "V".into();
    let result = analyzer().assess_detailed(&input, &context()).unwrap();
    assert!(result.measurements["Ch0"].variance_uv2.unwrap().is_finite());
    assert_eq!(result.signal_quality.overall_score, UnitInterval::ZERO);
    serde_json::to_string(&result).unwrap();
}

#[test]
fn spectral_ratios_are_energy_weighted_across_epochs_and_handle_nyquist_mixtures() {
    let mut row = sine(256.0, 10.0, 10.0, 512);
    row.extend(sine(256.0, 50.0, 100.0, 512));
    let result = analyzer()
        .assess_detailed(&recording(256.0, vec![row]), &context())
        .unwrap();
    close(
        result.measurements["Ch0"]
            .line_power_fraction
            .unwrap()
            .get(),
        10_000.0 / 10_100.0,
        1e-7,
    );

    let row = sine(256.0, 10.0, 20.0, 1024)
        .iter()
        .enumerate()
        .map(|(n, value)| value + if n % 2 == 0 { 20.0 } else { -20.0 })
        .collect();
    let result = analyzer()
        .assess_detailed(&recording(256.0, vec![row]), &context())
        .unwrap();
    close(
        result.measurements["Ch0"]
            .high_frequency_power_fraction
            .unwrap()
            .get(),
        2.0 / 3.0,
        1e-7,
    );
}

#[test]
fn zero_padding_does_not_hide_insufficient_line_frequency_resolution() {
    let config = QualityConfig {
        window_seconds: 0.125,
        ..QualityConfig::default()
    };
    let input = recording(256.0, vec![sine(256.0, 10.0, 20.0, 1024)]);
    let result = QualityAnalyzer::new(config)
        .unwrap()
        .assess_detailed(&input, &context())
        .unwrap();
    assert_eq!(result.measurements["Ch0"].line_power_fraction, None);
    assert!(has_warning(
        &result.signal_quality.channel_quality["Ch0"],
        "LINE_BAND_UNAVAILABLE"
    ));
    assert!(result.signal_quality.overall_score.get() <= 0.5);
}
